# Generated by Django 3.1.5 on 2021-02-03 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20210127_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='Company', max_length=3000),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='job', max_length=3000),
        ),
        migrations.AlterField(
            model_name='job',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 3, 11, 55, 48, 312530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(default='not specified', max_length=3000),
        ),
    ]
